### ISSUE TITLE
Point totals no longer updating after user tags added

### ISSUE THREAD

**Issue by mnemnion** [etcet/HNES#112]
My copy of HNES is no longer updating the point totals for users (upvotes and downvotes no longer affect the displayed point total).

It may be a false correlation, but I recall this starting right around when 'flair' tags got added to usernames. 

I'm running Chrome on OS X Yosemite.

**Comment by ibejoeb** [comment]
@MaximeKjaer This is indeed the case.  Do you any time to investigate?

**Comment by MaximeKjaer** [comment]
All right, I can reproduce this in my fork, so I must have be the one who introduced the bug. I'll definitely investigate it, and submit a PR once I've fixed it.

**Comment by MaximeKjaer** [comment]
I think I've found the source of the bug, and it doesn't stem from my PR. I'm going to commit my fix, send a PR and explain the source of the bug there :smile:

**Comment by ibejoeb** [comment]
Plot thickens... cheers!
