### ISSUE TITLE
Don't like custom theme. Why not allow default HN theme?

### ISSUE THREAD

**Issue by MarcoPeraza** [etcet/HNES#116]
I love so much about this extension but I strongly dislike the custom styling, so much so that I've uninstalled the extension.  How about letting users use the standard HN theme? (are you even sure that users like the custom theme? maybe people just put up with it for the other features). Just some food for thought. Nice work with the extension all around though!

**Comment by etcet** [comment]
I know I like the custom styling :)
It looks like they're finally adding some of this extensions features into regular old HN so you won't need to use this extension and this theme. Unfortunately I didn't design the extension to support themes and it wouldn't be easy to remove the custom styling and layout at this point.
