### ISSUE TITLE
New HN layout/features breaks HNES

### ISSUE THREAD

**Issue by c17r** [etcet/HNES#117]
HN announcement: https://news.ycombinator.com/item?id=12073675

When looking at the comments page:
- HNES version of collapse/expand no longer shows
- HNES highlighting of new comments no longer shows
- Story text and top-level comment box shoved flush right
- Going to https://news.ycombinator.com/threads?id=_username_ shows a blank page

**Comment by c17r** [comment]
In one of the threads dang mentioned they are considering the "highlighting of new comments" as a core feature as well.

**Comment by ibejoeb** [comment]
I have a new branch that actually does not break, but the presentation is a little wonky.  I've been working through some of the features, and new-comment highlighting is next.

**Comment by ibejoeb** [comment]
Seems like dang is saying they're adding new-comment highlighting directly.

https://news.ycombinator.com/item?id=12073934

**Comment by c17r** [comment]
Hence my comment above 😄

**Comment by ibejoeb** [comment]
Misunderstood, thought you were talking about unfulfilled request.

**Comment by etcet** [comment]
I've fixed the item and threads pages in https://github.com/etcet/HNES/commit/2041f92c9623afbb746a48e7b938c8a5695ce038. I think there's just fixing favorites (issue 120) and perhaps testing the performance of the new collapse and use whichever is best. It may make more sense to use the new functionality and drop ours.

**Comment by c17r** [comment]
I'd probably stick to use the native collapse instead of HNES but would move it from the right side of the name to the left.
