### ISSUE TITLE
Missing vote/comment counts?

### ISSUE THREAD

**Issue by diego898** [etcet/HNES#123]
Some strange behavior just started?

<img width="1084" alt="screen shot 2016-08-13 at 3 25 18 pm" src="https://cloud.githubusercontent.com/assets/742407/17645956/2b76eb64-616a-11e6-9330-585db115be1e.png">

**Comment by bsloane1650** [comment]
I believe this is due to HN chaninge the space character to a non breaking space (charCode 160)

I have submitted a pull request to fix this issue.

https://github.com/etcet/HNES/pull/124

**Comment by bsloane1650** [comment]
@masongup improved my fix. Use https://github.com/etcet/HNES/pull/126 instead.

**Comment by etcet** [comment]
Fixed in #126
