### ISSUE TITLE
Reply box appears to the left of parent comment text

### ISSUE THREAD

**Issue by tedmiston** [etcet/HNES#127]
I have been experiencing this issue in Chrome for a while (I think since I installed HNES).

The reply text box appears to the left of the parent text.

![screen shot 2016-08-17 at 12 42 18 pm](https://cloud.githubusercontent.com/assets/366688/17745015/3d559752-6478-11e6-9df3-ef2477ca1465.png)

It seems like it should be aligned underneath it (I've modified the html here to make that so):

![screen shot 2016-08-17 at 12 42 39 pm](https://cloud.githubusercontent.com/assets/366688/17745030/47be7e8e-6478-11e6-9ad6-f17d5a086108.png)

The only thing I changed was the `<td>` `colspan` from 1 to 2 to align with parent text row above.

I'm happy to submit a PR for this if desired.

**Comment by etcet** [comment]
dupe #121
