### ISSUE TITLE
HNES Availability on Mozilla Addons

### ISSUE THREAD

**Issue by uzegonemad** [etcet/HNES#139]
@etcet Now that HNES is Firefox-ready, what's the best way to get it published on AMO  (addons.mozilla.org)? Would you be willing to publish it, or would you prefer delegating the task?

[This article](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension) has the required steps, but the gist of it is:

1. Create an account on AMO
1. Zip the repo (Firefox uses the cwd, not the parent folder like Chrome)
1. Upload, sign & publish

I'm happy to do so if you don't want to or don't have the time.

**Comment by sinistersnare** [comment]
Bump! Is there any news on this? I would love to have a way to download this from AMO.

**Comment by etcet** [comment]
I've had to upgrade to latest jquery and I've fixed some Firefox specific bugs but I've added it to AMO. It's currently in review.
