### ISSUE TITLE
"o" shortcut opens /undefined instead of page

### ISSUE THREAD

**Issue by kotoole1** [etcet/HNES#185]
After selecting a row with the j/k keys, the "o" key is supposed to open the link (like the "c" key opens the comments).

As of a few months ago, instead the shortcut opens https://news.ycombinator.com/undefined, a page which just contains the word "unknown."

Happens in chrome, both windows and mac versions.

**Comment by chaseha** [comment]
Same issue has broken the other keyboard shortcuts that open links ("l", "b")

Keyboard navigation was the main benefit of this extension, IMO. Any forks that fix this?

**Comment by kotoole1** [comment]
https://github.com/etcet/HNES/pull/186

It's a one-line fix, let's see if @etcet is still alive enough to click merge. Would rather not hard fork.

**Comment by etcet** [comment]
I'm alive enough to click merge but publishing to the web stores will need to wait until after the holidays

**Comment by chaseha** [comment]
Sounds good - thank you both!

**Comment by kotoole1** [comment]
Excellent, thank you very much!

**Comment by etcet** [comment]
I've submitted the extension for review on firefox and chrome web store, thanks for the fix @kotoole1
