### ISSUE TITLE
Point numbers on index page not aligned/properly padded

### ISSUE THREAD

**Issue by tomkinsc** [etcet/HNES#3]
The point numbers on the index page are not aligned properly for me. I'm running Chrome version 23.0.1251.2 dev-m.

Here's a screenshot:
http://i.imgur.com/WveHe.png

And to be honest, I'd rather have the point values to the right side of the link titles anyway since I trust HN ranking and do not look at the point values very often (having the comment numbers is great, however).

**Comment by etcet** [comment]
Haven't seen this in a while.
