### ISSUE TITLE
Tables not lining up correctly

### ISSUE THREAD

**Issue by vincentmac** [etcet/HNES#4]
I just saw this extension on HN (of course) and tried it out.  It looks pretty good, however, I ran into one little issue: the tables aren't lining up correctly.  Please see the attached photo below:

https://www.box.com/s/bd724o3oh0rlhbmqezef

Chrome Dev: 23.0.1251.2 dev
Screen Resolution is 1920x1200

**Comment by etcet** [comment]
Haven't seen this in a while.
