### ISSUE TITLE
Feature Req - Add a Send to Pocket button

### ISSUE THREAD

**Issue by mikekhristo** [etcet/HNES#47]
The Pocket app (getpocket.com) is seriously awesome, especially for people on the go. Adding a 1-click send to pocket would be awesome. 

http://getpocket.com/developer/

**Comment by etcet** [comment]
Sorry, I'm not interested with integrating with any third parties.

**Comment by adityamenon** [comment]
Would you accept a PR that did this if I wrote it @etcet?
