### ISSUE TITLE
HNES seems to break randomly for a few days then fix itself

### ISSUE THREAD

**Issue by kevinkenny** [etcet/HNES#48]
Every now again HNES seems to break. The first hint of this happening is when the background colour changes from HN's usual "mustard" tint to a much lighter, almost white colour. Then eventually this happens:

http://imgur.com/d6dnfRg

And the extension is more or less unusable.

I'm running the latest vesion (1.2.0.14). If I disable the extension for a few days then re-enable, everything seems to right itself.

I'm not sure if HN tinker with their CSS or table layout periodically causing the extension to trip up. I did try to debug this but front end hacking is not my forte.

I'm running with Windows 7 Ultimate x64 and Chrome 32.

**Comment by etcet** [comment]
This generally happens either due to incompatibility with other plugins or due to HN's markup changing. There's no real solution but to re-write using the API instead.
