### ISSUE TITLE
How to use on Firefox?

### ISSUE THREAD

**Issue by sergiotapia** [etcet/HNES#54]
Hey there, I use this a lot on Chrome - but I was wondering if it's possible to use on Firefox?

**Comment by sergiotapia** [comment]
Bump! How's it going? :wink:

**Comment by sornars** [comment]
@jonafato Is any further work required to have this packaged as a Firefox extension? I've just loaded it as an unofficial addon and it seems to be working as expected. Happy to take a stab at fixing any outstanding issues but I'm not sure what things would need to be addressed.

**Comment by yoasif** [comment]
Firefox now uses a Chrome-like API (WebExtensions) for their add-ons: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

There seems to be more interest: https://news.ycombinator.com/item?id=15695706

**Comment by etcet** [comment]
It's now available on Firefox: https://addons.mozilla.org/en-US/firefox/addon/hnes/
