### ISSUE TITLE
Age of posts not shown

### ISSUE THREAD

**Issue by sekrause** [etcet/HNES#58]
When I install HNES it's front page doesn't show the age of posts (e.g. "6 hours ago") anymore. However, that's some very useful information I would still like to see.

**Comment by r04r** [comment]
Age of the post is now shown instead of comment counts? Very confusing.

**Comment by gtd** [comment]
:+1:  I also would like to still see the age.

**Comment by etcet** [comment]
I'm not sure when this was fixed but the 'x hours ago' text shows now
