### ISSUE TITLE
infinite scroll

### ISSUE THREAD

**Issue by so0k** [etcet/HNES#63]
just started visiting hacker news - been using reddit for ages and was looking for infinite scroll 

expected this to come with the enhancement suite, but seems its not available. Couldn't find any previous issues talking about it either.

might be interesting to add:
https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/5751e2cbda3df81e5915546b241a2362ca1a7176/lib/modules/neverEndingReddit.js

https://github.com/gabrielecirulli/hn-special/blob/43ef6f781cdf8bc996bab4c3a5f996a6d24e93de/lib/modules/infinite_scrolling.js

**Comment by etcet** [comment]
I'm sorry but I don't like infinite scrolling due to it breaking footers.

**Comment by so0k** [comment]
ok :) thanks for the feedback

**Comment by so0k** [comment]
could be a user configurable option, I might for and PR - but I might be too busy
