### ISSUE TITLE
domains have last char truncated

### ISSUE THREAD

**Issue by seanjensengrey** [etcet/HNES#65]
...ight (arxiv.or)
Lisp: A Cult I Almost Joined (2005) (fluff.inf) by rlander

On Sun Jan 18 18:52:50 PST 2015

I noticed that extracted domain has the last character removed.

**Comment by alanc10n** [comment]
I made a pull request to fix this issue. In the event that the extension doesn't get updated in the Chrome store soon, it's pretty easy to load a fixed copy. You can grab from the branch of the PR, pull up chrome://extensions, enable developer mode, click on "Load unpacked extension", and browse to the directory you cloned to. You'd of course want to disable the existing HNES extension first.

**Comment by engstrom** [comment]
:+1:

**Comment by seanjensengrey** [comment]
:+1:

**Comment by etcet** [comment]
Thanks alanc10n!
