### ISSUE TITLE
Comment upvote count is floating to the right of the comment 

### ISSUE THREAD

**Issue by dmix** [etcet/HNES#67]
I noticed that the points count next to comments went from the left side to the right recently:

![screenshot from 2015-01-21 20 08 16](https://cloud.githubusercontent.com/assets/12528/5848722/b0961fa4-a1a9-11e4-8258-15da315a223e.png)

I don't see a commit message for this so I'm guessing it's a bug?

**Comment by etcet** [comment]
Thanks for reporting this bug! It should be fixed now.
