### ISSUE TITLE
Comments not posting

### ISSUE THREAD

**Issue by gregpinero** [etcet/HNES#70]
I can write out a comment and hit submit but then it never shows up anywhere.  This seems to be a new issue within the past days/weeks?

**Comment by dpmccabe** [comment]
I'm having this problem, but only sporadically. The comment is also irretrievable when I hit the back button.

**Comment by anugupta** [comment]
Yeah, I'm experiencing the same problem as @dpmccabe - probably for the last week or so.

**Comment by masongup** [comment]
I think this is the same as my issue 71. I'm not sure exactly when it started, but I think it's around a few weeks ago.

**Comment by etcet** [comment]
I'd just like to confirm that this is in-line replies only, right? If so, it should be resolved in commit 123d667c50c411377de8f1a01bbafb474ac3dabb

**Comment by dpmccabe** [comment]
Correct, I only ever noticed it in that case. Top-level comments still work.

**Comment by etcet** [comment]
Thanks for the confirmation, I've pushed it to the Chrome store so it should be updated within the next couple of hours.
