### ISSUE TITLE
Inline replies are broken

### ISSUE THREAD

**Issue by masongup** [etcet/HNES#71]
When you click reply, HNES creates an inline reply box. When I try to submit a new post from this, it doesn't appear on the page, and I can't use back or anything to get the text back - it's just gone. Replying from the box at the top of an item page - either a full thread, or an individual comment - works fine.

I'm getting this behavior on Chrome stable on Mac OS and Windows 7.

I might take a look at this myself, if you're open to a pull request.

**Comment by runeb** [comment]
HN form params have changed. Quote from HN devs regarding comments not being posted:

`We figured it out but you'll need to stop using (or fix) HNES. It looks for things that aren't there anymore and hides the failures from you. In this case it was some parameter changes in our forms. `

**Comment by etcet** [comment]
When I first made HNES, HN hadn't changed its front end for years and I was unemployed. Now, they're introducing breaking (well breaking HNES) changes on a weekly or monthly basis and I have far less time to work out the issues. I'll look into this today but I sure wish they would stop mucking about.

**Comment by etcet** [comment]
Should be resolved in commit 123d667c50c411377de8f1a01bbafb474ac3dabb. They renamed 'whence' to 'goto'. Please let me know if there are any persisting or further issues.

**Comment by masongup** [comment]
The update came down from the Chrome store, can confirm that it works. Thanks for the quick fix!
