### ISSUE TITLE
Days since submission shown instead of number of comments

### ISSUE THREAD

**Issue by hatboysam** [etcet/HNES#75]
https://news.ycombinator.com/submitted?id=habosa

When I go to my submissions page it shows a weird number in place of the # of comments for submissions that got no comments.  It may be a coincidence, but for the ones I have checked it is equal to the number of days since submission.

**Comment by shazeline** [comment]
I am experiencing the same issue. It's worth noting that this only occurs for posts that have 0 comments. For posts with at least 1 comment, the correct number is shown.

**Comment by shazeline** [comment]
It looks like they modified the structure again.

https://news.ycombinator.com/submitted?id=aaronbrethorst

"[int: num] days ago | discuss" - indicates 0 comments and post was recent (looks like 2 weeks)
"[int: num] days ago | [int: c] comments" - indicates c comments
"[int: num] days ago | comments" - indicates at least 1 comment
"[int: num] days ago" - indicates 0 comments and post was not recent (more than 2 weeks ago).

Why all four of these exist is beyond me. It might be worth revisiting this in a week or two to see if things have stabilized.
