### ISSUE TITLE
Spacing is off between comments, and Karma Corner is styled oddly

### ISSUE THREAD

**Issue by Redoubts** [etcet/HNES#79]
See screenshot. Comments have way too much space between themselves. Also, the top right corner looks like the style ran over or something.
![screen shot 2015-04-15 at 6 49 15 pm](https://cloud.githubusercontent.com/assets/2435101/7172665/7c820a78-e3a0-11e4-8cf6-86649266b225.png)

**Comment by etcet** [comment]
Fixed in d6aa5ae6775f5babc03ca52fbb39a045c5276403 and 9064041e9ad54d4307acbc3987596eb75c876a68. Thanks for the report!
