### ISSUE TITLE
Comment spacing issue

### ISSUE THREAD

**Issue by JoshSchreuder** [etcet/HNES#80]
Looks like something broke the spacing on comments as of today.

EG:
https://news.ycombinator.com/item?id=9385538
![image](https://cloud.githubusercontent.com/assets/681706/7174145/0a20187a-e446-11e4-86d0-d33f8db9bcec.png)

https://news.ycombinator.com/item?id=9382933
![image](https://cloud.githubusercontent.com/assets/681706/7174147/156144f2-e446-11e4-8aee-355eb648dca6.png)

Every comment thread appears to be like this.

**Comment by JoshSchreuder** [comment]
Never mind, fixed by @d6aa5ae6775f5babc03ca52fbb39a045c5276403 in v1.3.4.7 :smile:

**Comment by etcet** [comment]
Thanks for the report anyway!
