### ISSUE TITLE
Open links in new tab

### ISSUE THREAD

**Issue by mihai-scurtu** [etcet/HNES#89]
This is really bugging me on my macbook where I can't middle click. 

Personally I'd like this to be default behavior and I can submit a PR to make it so over the weekend, if that's okay.

**Comment by mihai-scurtu** [comment]
I can also try adding a simple options page and add it as an option.

**Comment by etcet** [comment]
Hi Mihai, there's a keyboard shortcut for this if you use the j,k, and l keys to navigate links.
