### ISSUE TITLE
New tab fails to render

### ISSUE THREAD

**Issue by bsloane1650** [etcet/HNES#93]
When attempting to visit the new tab, HNES fails to render, causing a solid white screen to display instead.

I have isolated the problem to HNES's attempt to handle dead submissions, where it incorrectly parses the URL to be what is provided by the "web" link below the title, which currently points to google, not an HN comment section. This causes an exception when HNES attempts to count the comments that the submission has, causing the page to fail to render. 

I have implemented a workaround here:
https://github.com/etcet/HNES/pull/92

which checks for invalid links when HNES counts comments. This still leaves a slight artifact where the comment count is (currectly) not visible, but still a clickable link to the google search.

**Comment by etcet** [comment]
Thanks! It'd be nice to support the flag, vouch, past, and web links on https://news.ycombinator.com/newest (https://github.com/etcet/HNES/issues/94) but this works for now.
