### ISSUE TITLE
keyboard shortcut for upvote

### ISSUE THREAD

**Issue by chaseha** [etcet/HNES#97]
Would be very nice if while browsing frontpage (and eventually comments) with keyboard shortcuts, you could upvote comments with a Keyboard Shortcut like in RES. Maybe using the same keys, 'A' for upvote and 'Z' for downvote (if you had sufficient karma)

**Comment by etcet** [comment]
I'm sorry but I'm reluctant to include more keyboard shortcuts. I'd remove all of those already in there if possible.
